version = "1.2.7"
builder = "spa"

[template_settings]
autoreload = "1"
background-color = "#121414"
custom-color = "#f3a833"
accent-color = "#2D4566"
highlight-color = "#73bed3"
text-color = "#c7cfcc"
subheader-text = "Curated news for developers. Updated every hour"
repo-url = "https://github.com/exaroth/awesome-dev.news"
header-svg = "/awesome-dev.news/assets/logo.svg"
