version = "1.2.8"
builder = "spa"

[template_settings]
text-color = "#c7cfcc"
header-svg = "/assets/logo.svg"
background-color = "#121414"
highlight-color = "#73bed3"
subheader-text = "Curated news for developers. Updated every hour"
custom-color = "#f3a833"
autoreload = "1"
accent-color = "#2D4566"
repo-url = "https://github.com/exaroth/awesome-dev.news"
